// <auto-generated />
namespace FormDemoProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FormTableUpdated4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FormTableUpdated4));
        
        string IMigrationMetadata.Id
        {
            get { return "201902152205211_FormTableUpdated4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
